apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: app
          image: server:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
